name: Android CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Настройка Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Gradle
        run: chmod +x gradlew

      - name: Ktlint
        run: ./gradlew ktlintCheck

      - name: Detekt
        run: ./gradlew detekt

      - name: Android Lint
        run: ./gradlew lintDebug

      # --------------------------------

  build-and-test:
    needs: code-quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Настройка Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Gradle
        run: chmod +x gradlew

      - name: Unit тесты
        run: ./gradlew testDebugUnitTest

      - name: Сборка отладочного APK
        run: ./gradlew assembleDebug

      - name: Сборка релизного AAB
        run: ./gradlew bundleRelease

      - name: Сохранение Debug APK в артефакты
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Сохранение Release AAB в артефакты
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: app/build/outputs/bundle/release/app-release.aab